[project]
name = "lol-black-bars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=10.0.0",
    "pystray>=0.19.0",
    "pywin32>=311",
]
